### ISSUE TITLE
PHP Stacktraces enabled + PHPMailer issues

### ISSUE THREAD

**Issue by gianklug** [Lugigiiii/logbook#1]
When setting both the email and username field to an email, PHPMailer fails:
```php
HTTP/2 200 OK
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Vary: Accept-Encoding
Content-Type: text/html; charset=UTF-8
Date: Tue, 29 Aug 2023 05:48:29 GMT
Server: Apache

PHPMailer\PHPMailer\Exception: Invalid address:  (cc):  in /home/azumusis/www/logbook.lacasaverde.ch/resources/php/phpmailer/PHPMailer.php:1094
Stack trace:
#0 /home/azumusis/www/logbook.lacasaverde.ch/resources/php/phpmailer/PHPMailer.php(1029): PHPMailer\PHPMailer\PHPMailer->addOrEnqueueAnAddress('cc', NULL, NULL)
#1 /home/azumusis/www/logbook.lacasaverde.ch/resources/php/functions/main-functions.php(631): PHPMailer\PHPMailer\PHPMailer->addCC(NULL, NULL)
#2 /home/azumusis/www/logbook.lacasaverde.ch/resources/php/functions/main-functions.php(1167): insertNewUser('Get', 'Hacked', 'test@gk.wtf', 'test@gk.wtf', '0')
#3 {main}
```

Also PHP stack traces should be disabled in a production environment as they can leak sensitive information.

**Comment by Lugigiiii** [comment]
fixed in test environment
